name: Infrastructure Provisioning
'on':
  workflow_dispatch:
    branches:
    - main
    inputs:
      service_project_configuration:
        required: true
        type: string
env:
  REPOSITORY_DETAILS: "{\n        \"owner\": \"mayanklbg\",\n        \"user_email\": \"mayank.agarwal@e.lloydsbanking.com\",\n        \"repo_name\": \"test-gh-api\",\n        \"main_branch\": \"main\",\n        \"new_branch\": \"CPE-001\",\n        \"gh_token\": \"${{ github.event.inputs.gh_token }}\",\n        \"commit_message\": \"feat: CPE-001, Update docker file\",\n        \"description\": \"This change is intented to update docker file for it's base image\",\n        \"path_to_commit_data\": data_file_to_commit,\n    }"
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      id: checkout
        
    - name: Clone Workflow Setup Repository
      id: clone_workflow_repo
      run: |
        git clone -b CPE-355 --single-branch https://${{ github.actor }}:${{ secrets.GH_TOKEN }}@github.com/lbg-cloud-platform/vdc-github-workflows-setup.git

    - name: Install Python dependencies
      id: pip_install
      run: |
        python -m pip install --upgrade pip
        if [ -f vdc-github-workflows-setup/scripts/requirements.txt ]; then pip install -r vdc-github-workflows-setup/scripts/requirements.txt; fi

    - name: Generate pull request
      id: create_pr
      run: |
        python vdc-github-workflows-setup/scripts/pipeline_setup.py "infra" "${{ github.event.inputs.service_project_configuration }}" "$REPOSITORY_DETAILS"
