name: Infrastructure Provisioning
'on':
  workflow_dispatch:
    branches:
    - main
    inputs:
      service_project_configuration:
        required: true
        type: string
env:
  REPOSITORY_DETAILS = "VAL"
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      id: checkout
        
    - name: Clone Workflow Setup Repository
      id: clone_workflow_repo
      run: |
        git clone -b CPE-355 --single-branch https://${{ github.actor }}:${{ secrets.GH_TOKEN }}@github.com/lbg-cloud-platform/vdc-github-workflows-setup.git

    - name: Install Python dependencies
      id: pip_install
      run: |
        python -m pip install --upgrade pip
        if [ -f vdc-github-workflows-setup/scripts/requirements.txt ]; then pip install -r vdc-github-workflows-setup/scripts/requirements.txt; fi

    - name: Generate pull request
      id: create_pr
      run: |
        python vdc-github-workflows-setup/scripts/pipeline_setup.py "infra" "${{ github.event.inputs.service_project_configuration }}" $REPOSITORY_DETAILS
