name: Infrastructure Provisioning
'on':
  workflow_dispatch:
    branches:
    - main
    inputs:
      service_project_configuration:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check Input
      run: |
        echo '${{ toJSON(github.event.inputs.service_project_configuration) }}'
        
    - name: Clone Workfloe Setup Repository
      id: clone_setu_repo
      run: |
        git clone -b dev --single-branch git@github.com:${{ github.actor }}/lbg-cloud-platform/vdc-github-workflows-setup.git
        # git clone git@github.com:${{ github.actor }}/repo.git
