name: Infrastructure Provisioning
'on':
  workflow_dispatch:
    branches:
    - main
    inputs:
      service_project_configuration:
        required: true
        type: string
env:
  REPO_OWNER_TO_COMMIT: "mayanklbg"
  REPO_NAME_TO_COMMIT: "test-gh-api"
  MAIN_BRANCH: "main"
  NEW_BRANCH: "CPE-001"
  COMMIT_MESSAGE: "feat CPE-001, Update docker file"
  DESCRIPTION: "This change is intended to update docker file for it's base image"
  PATH_TO_COMMIT: "data_file_to_commit"

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      id: checkout
        
    - name: Clone Workflow Setup Repository
      id: clone_workflow_repo
      run: |
        git clone -b CPE-355 --single-branch https://${{ github.actor }}:${{ secrets.GH_TOKEN }}@github.com/lbg-cloud-platform/vdc-github-workflows-setup.git

    - name: Install Python dependencies
      id: pip_install
      run: |
        python -m pip install --upgrade pip
        if [ -f vdc-github-workflows-setup/scripts/requirements.txt ]; then pip install -r vdc-github-workflows-setup/scripts/requirements.txt; fi

    - name: Generate pull request
      id: create_pr
      run: |
        echo $( jq -n \
                  --arg repo_owner "$REPO_OWNER_TO_COMMIT" \
                  --arg repo_name "$REPO_NAME_TO_COMMIT" \
                  --arg main_branch "$MAIN_BRANCH" \
                  '{repo_owner: $repo_owner, repo_name: $repo_name, main_branch: $main_branch}' )
       
