name: Infrastructure Provisioning
'on':
  workflow_dispatch:
    branches:
    - main
    inputs:
      service_project_configuration:
        required: true
        type: string

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - name: Check Input
      run: |
        echo '${{ toJSON(github.event.inputs.service_project_configuration) }}'
        
    - name: Clone Workflow Setup Repository
      id: clone_setup_repo
      run: |
        git clone -b CPE-355 --single-branch https://${{ github.actor }}:${{ secrets.GH_TOKEN }}@github.com/lbg-cloud-platform/vdc-github-workflows-setup.git

  deploy:
    runs-on: ubuntu-latest
    needs: [setup]
    steps:
    - name: Create PR
      run: |
        cd vdc-github-workflows-setup
        ls
