name: Infrastructure Provisioning
'on':
  workflow_dispatch:
    branches:
    - main
    inputs:
      service_project_configuration:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check Input
      run: |
        echo '${{ toJSON(github.event.inputs.consumerId) }}'
