name: Infrastructure Provisioning
'on':
  workflow_dispatch:
    branches:
    - main
    inputs:
      service_project_configuration:
        required: true
        type: string

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:        
    - name: Check conversion
      id: clone_workflow_repo
      run: |
        service_project_configuration=$(echo "$(jq -c '.service_project_configuration | fromjson' ${{ github.event.inputs }})")
        echo $service_project_configuration
        
