name: Infrastructure Provisioning
'on':
  workflow_dispatch:
    branches:
    - main
    inputs:
      service_project_configuration:
        required: true
        type: string

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      id: checkout
        
    - name: Clone Workflow Setup Repository
      id: clone_workflow_repo
      run: |
        git clone -b CPE-355 --single-branch https://${{ github.actor }}:${{ secrets.GH_TOKEN }}@github.com/lbg-cloud-platform/vdc-github-workflows-setup.git

    - name: Create PR
      id: create_pr
      run: |
        cat Dockerfile
